title: "CS229 Machine Learning Notes"
description: "My personal documentation for Stanford's CS229 course"
url: "https://<yourusername>.github.io"
baseurl: "/cs229-notes"

remote_theme: tomjoht/documentation-theme-jekyll

# Sidebar settings
sidebar: sidebar
markdown: kramdown
highlighter: rouge
