title: "Machine Learning Notes"
description: "My personal documentation for Machine Learning course"
url: "https://sanjanb.github.io"
baseurl: "/MachineLearning-Notes"

remote_theme: tomjoht/documentation-theme-jekyll

# Sidebar settings
sidebar: sidebar
markdown: kramdown
highlighter: rouge
