title: "CS229 Machine Learning Notes"
description: "Notes for Stanford CS229 — Machine Learning"
url: "https://<yourusername>.github.io"
baseurl: "/cs229-notes"

remote_theme: olivier3lanc/Jekyll-LibDoc

# Optional: configure LibDoc settings (e.g. logo, search, etc.)
